name: Integration tests

on:
  pull_request:
  push:
    branches-ignore:
      - 'dependabot/**'
      - 'pre-commit-ci-update-config'
  workflow_dispatch:

jobs:
  integration_test:
    # if: ${{ contains(github.event.pull_request.labels.*.name, 'run-integration-tests') || github.event_name == 'workflow_dispatch' }}
    name: Integration tests
    strategy:
      matrix:
        EXTENSION_VERSION: ['release', 'dev']
        HYPERSPY_VERSION: ['release', 'RnM', 'RnP']
    # Use the "reusable workflow" from the hyperspy organisation
    uses: hyperspy/.github/.github/workflows/integration_tests.yml@main
    with:
      EXTENSIONS: 'exspy holospy lumispy'
      EXTENSION_VERSION: ${{ matrix.EXTENSION_VERSION }}
      HYPERSPY_VERSION: ${{ matrix.HYPERSPY_VERSION }}
      USE_CONDA: false




